const dataSocketActionTypes = {
    CONNECTION_SOCKET: "CONNECTION_SOCKET",
    SET_NEW_DATA_SYMBOL_CHART_TOP: "SET_NEW_DATA_SYMBOL_CHART_TOP",
    SET_DATA_SYMBOL_CHART_TOP: "SET_DATA_SYMBOL_CHART_TOP",
    CHANGE_SYMBOL_CHART_TOP: "CHANGE_SYMBOL_CHART_TOP"
};

export default dataSocketActionTypes;