FROM node:10.16-alpine

#RUN apk add git
#RUN apk add openssh

ENV PATH_APP /home/app/
ENV NAME_APP bot_binance_frontend
ENV FULL_PATH ${PATH_APP}${NAME_APP}/
ENV ENTRY_POINT_SERVER ${FULL_PATH}/src/App.js

WORKDIR ${FULL_PATH}
COPY . .

RUN if [ ! -e ${ENTRY_POINT_SERVER} ]; then cd ${PATH_APP} && npx create-react-app ${NAME_APP}; fi

RUN apk add --update bash
RUN apk add --update nano

EXPOSE 3000