FROM node:10.16-alpine

ENV PATH_APP /home/app/
ENV NAME_APP bot_binance_api
ENV FULLPATH ${PATH_APP}${NAME_APP}
WORKDIR ${FULLPATH}/

COPY . .

RUN if [ ! -e ${FULLPATH}/app.js ]; then cd $PATH_APP && npx express-generator $NAME_APP ; fi

RUN npm install
#RUN if [ -e $PATH_APP$NAME_APP/package.json ]; then npm start ; fi

EXPOSE 3000
CMD [ "npm", "start"]

