FROM node:10.16-alpine

ENV PATH_APP /home/app/
ENV NAME_APP bot_binance_api
ENV FULL_PATH ${PATH_APP}${NAME_APP}
ENV ENTRY_POINT_SERVER ${FULL_PATH}/src/start.ts
WORKDIR ${FULL_PATH}/

COPY . .

WORKDIR ${PATH_APP}/
RUN if [ ! -e ${ENTRY_POINT_SERVER} ]; then npx express-generator-typescript $NAME_APP ; fi
WORKDIR ${FULL_PATH}/

RUN npm install
#RUN if [ -e $PATH_APP$NAME_APP/package.json ]; then npm start ; fi

EXPOSE 3000
CMD [ "npm", "start"]

