FROM node:10.16-alpine

ENV PATH_APP /home/app/
ENV NAME_APP bot_binance_tpl
ENV FULL_PATH ${PATH_APP}${NAME_APP}
ENV ENTRY_POINT_SERVER ${FULL_PATH}/src/index.js

WORKDIR ${FULL_PATH}
COPY . .

RUN if [ ! -e ${ENTRY_POINT_SERVER} ]; then cd ${PATH_APP} && npx create-react-app ${NAME_APP}; fi

EXPOSE 3000


